version: '3'
services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    hostname: netdata
    ports:
      - 19999:19999
    networks:
      - netdata-bridge
    environment:
     - PGID=999  # grep docker /etc/group | cut -d ':' -f 3 https://github.com/netdata/netdata/issues/5112#issuecomment-451442307
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    networks:
      - netdata-bridge
    user: nobody:nogroup
    volumes:
      - ./data/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    restart: always
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: grafana
    ports:
      - 3000:3000
    networks:
      - netdata-bridge
    user: root:root
    volumes:
      - ./data/grafana:/var/lib/grafana
    restart: always
networks:
  netdata-bridge:
    driver: bridge
